# Generated by Django 3.1.1 on 2020-11-05 06:16

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last_name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=50, verbose_name='phone')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('password', models.CharField(max_length=255, verbose_name='password')),
                ('state', models.CharField(max_length=255, verbose_name='state')),
                ('country', models.CharField(max_length=255, verbose_name='country')),
                ('company_name', models.CharField(max_length=255, verbose_name='company_name')),
                ('company_email', models.EmailField(max_length=254, verbose_name='company_email')),
                ('company_size', models.CharField(max_length=255, verbose_name='company_size')),
                ('company_type', models.CharField(max_length=255, verbose_name='company_type')),
                ('photo', models.ImageField(upload_to='uploads/photo/staffs/')),
                ('pin', models.IntegerField(verbose_name='PIN')),
                ('roles', models.CharField(max_length=255, verbose_name='roles')),
                ('expenditure', models.CharField(max_length=255, verbose_name='expenditure')),
                ('reward_sent', models.CharField(max_length=255, verbose_name='reward_sent')),
                ('unclaimed_funds', models.CharField(max_length=255, verbose_name='unclaimed_funds')),
                ('status', models.CharField(max_length=255, verbose_name='status')),
                ('ratings', models.CharField(max_length=255, verbose_name='ratings')),
                ('facebook', models.CharField(max_length=255, verbose_name='facebook')),
                ('instagram', models.CharField(max_length=255, verbose_name='instagram')),
                ('twitter', models.CharField(max_length=255, verbose_name='twitter')),
                ('youtube', models.CharField(max_length=255, verbose_name='youtube')),
                ('tiktok', models.CharField(max_length=255, verbose_name='tiktok')),
                ('snampmsgboard', models.CharField(max_length=255, verbose_name='snap_message_board')),
            ],
            options={
                'db_table': 'staffs',
            },
        ),
    ]
