# Generated by Django 3.1.1 on 2020-11-05 06:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created'),
        ),
        migrations.AddField(
            model_name='staffs',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_updated'),
        ),
    ]
