# Generated by Django 3.1.1 on 2020-11-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20201105_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='gender',
            field=models.IntegerField(default=1, verbose_name='gender'),
            preserve_default=False,
        ),
    ]
