# Generated by Django 3.1.1 on 2020-11-05 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_staffs_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_size', models.CharField(max_length=255, verbose_name='role_size')),
            ],
            options={
                'db_table': 'company_size',
            },
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(max_length=255, verbose_name='role_type')),
            ],
            options={
                'db_table': 'company_type',
            },
        ),
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_category', models.CharField(max_length=255, verbose_name='content_category')),
            ],
            options={
                'db_table': 'content_category',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_type', models.CharField(max_length=255, verbose_name='gender_type')),
            ],
            options={
                'db_table': 'gender',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=255, verbose_name='role_name')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.AddField(
            model_name='staffs',
            name='content_category',
            field=models.CharField(default='', max_length=255, verbose_name='content_category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffs',
            name='company_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.companysize'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='company_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.companytype'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.gender'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='roles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.roles'),
        ),
    ]
