# Generated by Django 3.1.1 on 2020-11-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20201105_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='birthday',
            field=models.DateField(verbose_name='DOB'),
            preserve_default=False,
        ),
    ]
