# Generated by Django 3.1.1 on 2020-11-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20201105_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysize',
            name='role_size',
        ),
        migrations.RemoveField(
            model_name='companytype',
            name='role_type',
        ),
        migrations.AddField(
            model_name='companysize',
            name='company_size',
            field=models.CharField(default='', max_length=255, verbose_name='company_size'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companytype',
            name='company_type',
            field=models.CharField(default='', max_length=255, verbose_name='company_type'),
            preserve_default=False,
        ),
    ]
