# Generated by Django 3.1.1 on 2020-11-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20201106_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='company_size',
            field=models.IntegerField(verbose_name='company_size'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='company_type',
            field=models.IntegerField(verbose_name='company_type'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='roles',
            field=models.IntegerField(verbose_name='roles'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='status',
            field=models.IntegerField(verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='creators',
            name='company_size',
            field=models.IntegerField(verbose_name='company_size'),
        ),
        migrations.AlterField(
            model_name='creators',
            name='company_type',
            field=models.IntegerField(verbose_name='company_type'),
        ),
        migrations.AlterField(
            model_name='creators',
            name='roles',
            field=models.IntegerField(verbose_name='roles'),
        ),
        migrations.AlterField(
            model_name='creators',
            name='status',
            field=models.IntegerField(verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='expenditure',
            field=models.FloatField(default=0, verbose_name='expenditure'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='reward_sent',
            field=models.FloatField(default=0, verbose_name='reward_sent'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='roles',
            field=models.IntegerField(verbose_name='roles'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='status',
            field=models.IntegerField(verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='unclaimed_funds',
            field=models.FloatField(default=0, verbose_name='unclaimed_funds'),
        ),
    ]
