# Generated by Django 3.1.1 on 2020-11-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20201106_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='company_size',
            field=models.IntegerField(verbose_name='company_size'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='company_type',
            field=models.IntegerField(verbose_name='company_type'),
        ),
    ]
