# Generated by Django 3.1.1 on 2020-11-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_roles_login_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='creators',
            name='levels',
            field=models.IntegerField(default=1, verbose_name='levels'),
        ),
    ]
