# Generated by Django 3.1.1 on 2020-11-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_creators_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels', models.IntegerField(default=1, verbose_name='levels')),
                ('badges', models.CharField(max_length=255, verbose_name='badges')),
                ('influencers', models.CharField(max_length=255, verbose_name='influencers')),
                ('content_creators', models.CharField(max_length=255, verbose_name='content_creators')),
            ],
            options={
                'db_table': 'badge_levels',
            },
        ),
        migrations.RemoveField(
            model_name='brands',
            name='content_category',
        ),
        migrations.RemoveField(
            model_name='creators',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='creators',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='creators',
            name='company_size',
        ),
        migrations.RemoveField(
            model_name='creators',
            name='company_type',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='content_category',
        ),
        migrations.AddField(
            model_name='creators',
            name='content_type',
            field=models.CharField(default='', max_length=255, verbose_name='content_type'),
            preserve_default=False,
        ),
    ]
