# Generated by Django 3.1.1 on 2020-11-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20201109_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentcategory',
            name='content_category',
        ),
        migrations.AddField(
            model_name='contentcategory',
            name='category_creator',
            field=models.CharField(default='', max_length=255, verbose_name='category_creator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentcategory',
            name='category_influencer',
            field=models.CharField(default='', max_length=255, verbose_name='category_influencer'),
            preserve_default=False,
        ),
    ]
