# Generated by Django 3.1.1 on 2020-11-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_auto_20201109_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortname', models.CharField(max_length=255, verbose_name='sortname')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('phonecode', models.IntegerField(default=1, verbose_name='phonecode')),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('country_id', models.IntegerField(default=1, verbose_name='country_id')),
            ],
        ),
    ]
