# Generated by Django 3.1.1 on 2020-11-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_countries_states'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='states',
            table='states',
        ),
    ]
