# Generated by Django 3.1.1 on 2020-11-09 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_auto_20201109_1700'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='states',
            table='states',
        ),
    ]
